name: 'Trigger Repo on child'

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'Submodules Sync' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Trigger workflow in custom_purchase
        run: |
          curl -X POST https://api.github.com/repos/Sanjana-ks/custom_purchase/actions/workflows/main.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.MY_TOKEN }} \
          --data '{"ref": "master"}'
